# Generated by Django 5.1.15 on 2026-05-10 20:08

import apps.accounts.managers
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="الإيميل")),
                ("first_name", models.CharField(max_length=50, verbose_name="الاسم الأول")),
                ("last_name", models.CharField(max_length=50, verbose_name="الاسم الأخير")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="الصيغة: 05XXXXXXXX أو +9665XXXXXXXX",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_phone",
                                message="رقم الجوال غير صحيح. الصيغة المقبولة: 05XXXXXXXX أو +9665XXXXXXXX",
                                regex="^(05|009665|9665|\\+9665)[0-9]{8}$",
                            )
                        ],
                        verbose_name="رقم الجوال",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("investor", "مستثمر"),
                            ("supervisor", "مشرف"),
                            ("manager", "مدير"),
                        ],
                        db_index=True,
                        default="investor",
                        max_length=20,
                        verbose_name="الدور",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("is_staff", models.BooleanField(default=False, verbose_name="موظف")),
                (
                    "is_email_verified",
                    models.BooleanField(default=False, verbose_name="تم تأكيد الإيميل"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستخدم",
                "verbose_name_plural": "المستخدمون",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", apps.accounts.managers.UserManager()),
            ],
        ),
    ]
