# Generated by Django 5.1.15 on 2026-05-10 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="اسم المعهد/الشركة"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, default="", max_length=50, verbose_name="المدينة"),
                ),
                ("bio", models.TextField(blank=True, default="", verbose_name="نبذة")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="الصورة الشخصية"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف شخصي",
                "verbose_name_plural": "الملفات الشخصية",
            },
        ),
    ]
