# Generated by Django 5.1.15 on 2026-05-10 20:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="اسم الباقة",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        help_text="يُولَّد تلقائياً من الاسم لو تُرك فارغاً",
                        max_length=120,
                        unique=True,
                        verbose_name="المعرّف (slug)",
                    ),
                ),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="السعر (ر.س)",
                    ),
                ),
                (
                    "duration_months",
                    models.PositiveSmallIntegerField(default=1, verbose_name="مدة الاشتراك (شهور)"),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="قائمة نصية بالمميزات — سطر لكل ميزة",
                        verbose_name="المميزات",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="packages/", verbose_name="الصورة"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(db_index=True, default=False, verbose_name="مميَّزة"),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="منشورة"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتيب العرض"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "باقة",
                "verbose_name_plural": "الباقات",
                "ordering": ["display_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"], name="packages_pa_is_acti_2fa163_idx"
                    )
                ],
            },
        ),
    ]
