# Generated by Django 5.1.15 on 2026-05-11 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="الصيغة: 05XXXXXXXX أو +9665XXXXXXXX",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_phone",
                                message="رقم الجوال غير صحيح. الصيغة المقبولة: 05XXXXXXXX أو +9665XXXXXXXX",
                                regex="^(05|009665|9665|\\+9665)[0-9]{8}$",
                            )
                        ],
                        verbose_name="رقم التواصل",
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="يُستخدم لزر واتساب العائم وفي الفوتر.",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_phone",
                                message="رقم الجوال غير صحيح. الصيغة المقبولة: 05XXXXXXXX أو +9665XXXXXXXX",
                                regex="^(05|009665|9665|\\+9665)[0-9]{8}$",
                            )
                        ],
                        verbose_name="رقم واتساب",
                    ),
                ),
                (
                    "snapchat_url",
                    models.URLField(
                        blank=True,
                        default="",
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="رابط سناب شات",
                    ),
                ),
                (
                    "x_url",
                    models.URLField(
                        blank=True,
                        default="",
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="رابط X",
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True,
                        default="",
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="رابط إنستقرام",
                    ),
                ),
                (
                    "tiktok_url",
                    models.URLField(
                        blank=True,
                        default="",
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="رابط تيك توك",
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        default="خوارزميات — منصة المعاهد · جميع الحقوق محفوظة",
                        max_length=160,
                        verbose_name="نص الحقوق",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخر تحديث")),
            ],
            options={
                "verbose_name": "إعدادات الموقع",
                "verbose_name_plural": "إعدادات الموقع",
                "ordering": ["-updated_at"],
            },
        ),
    ]
