# Generated by Django 5.1.15 on 2026-05-10 20:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("packages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="الاسم",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_phone",
                                message="رقم الجوال غير صحيح. الصيغة المقبولة: 05XXXXXXXX أو +9665XXXXXXXX",
                                regex="^(05|009665|9665|\\+9665)[0-9]{8}$",
                            )
                        ],
                        verbose_name="رقم الجوال",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="الإيميل")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد 🟠"),
                            ("in_progress", "جاري التواصل 🔵"),
                            ("closed", "تم الإغلاق 🟢"),
                            ("cancelled", "ملغي ❌"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="ملاحظات داخلية")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("landing", "الصفحة الرئيسية"),
                            ("profile", "ملف المستثمر"),
                            ("other", "آخر"),
                        ],
                        default="landing",
                        max_length=30,
                        verbose_name="المصدر",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IP"),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="User Agent"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "investor",
                    models.ForeignKey(
                        blank=True,
                        help_text="يُربَط تلقائياً لو كان المستخدم مسجَّلاً وقت الإرسال",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستثمر (إن وُجد)",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="packages.package",
                        verbose_name="الباقة",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب",
                "verbose_name_plural": "الطلبات",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="leads_lead_email_f663dc_idx"),
                    models.Index(fields=["phone"], name="leads_lead_phone_709d42_idx"),
                    models.Index(
                        fields=["status", "-created_at"], name="leads_lead_status_7559b2_idx"
                    ),
                ],
            },
        ),
    ]
