# Generated by Django 5.1.15 on 2026-05-10 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "جديد 🟠"),
                            ("in_progress", "جاري التواصل 🔵"),
                            ("closed", "تم الإغلاق 🟢"),
                            ("cancelled", "ملغي ❌"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="الحالة السابقة",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("new", "جديد 🟠"),
                            ("in_progress", "جاري التواصل 🔵"),
                            ("closed", "تم الإغلاق 🟢"),
                            ("cancelled", "ملغي ❌"),
                        ],
                        max_length=20,
                        verbose_name="الحالة الجديدة",
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("note", models.TextField(blank=True, default="", verbose_name="ملاحظة التغيير")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="غيّر بواسطة",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="leads.lead",
                        verbose_name="الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغيير حالة",
                "verbose_name_plural": "سجلات تغيير الحالة",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["lead", "-changed_at"], name="leads_statu_lead_id_8e588a_idx"
                    )
                ],
            },
        ),
    ]
